=== PulkitMathur/Databases/XML/asg2DTD.dtd
<?xml version="1.0" encoding="ISO-8859-1" ?>

<!ELEMENT PubmedArticleSet (PubmedArticle)>
<!ATTLIST PubmedArticleSet
  xmlns CDATA #FIXED ''>

<!ELEMENT PubmedArticle (MedlineCitation,PubmedData)>
<!ATTLIST PubmedArticle
  xmlns CDATA #FIXED ''>

<!ELEMENT MedlineCitation (PMID,DateRevised,Article,MedlineJournalInfo,
                           KeywordList)>
<!ATTLIST MedlineCitation
  xmlns CDATA #FIXED ''
  Owner NMTOKEN #REQUIRED
  Status NMTOKEN #REQUIRED>

<!ELEMENT PubmedData (History,PublicationStatus,ArticleIdList)>
<!ATTLIST PubmedData
  xmlns CDATA #FIXED ''>

<!ELEMENT PMID (#PCDATA)>
<!ATTLIST PMID
  xmlns CDATA #FIXED ''
  Version CDATA #REQUIRED>

<!ELEMENT DateRevised (Year,Month,Day)>
<!ATTLIST DateRevised
  xmlns CDATA #FIXED ''>

<!ELEMENT Article (Journal,ArticleTitle,ELocationID,Abstract,AuthorList,
                   Language,PublicationTypeList,ArticleDate)>
<!ATTLIST Article
  xmlns CDATA #FIXED ''
  PubModel NMTOKEN #REQUIRED>

<!ELEMENT MedlineJournalInfo (Country,MedlineTA,NlmUniqueID,
                              ISSNLinking)>
<!ATTLIST MedlineJournalInfo
  xmlns CDATA #FIXED ''>

<!ELEMENT KeywordList (Keyword)+>
<!ATTLIST KeywordList
  xmlns CDATA #FIXED ''
  Owner NMTOKEN #REQUIRED>

<!ELEMENT History (PubMedPubDate)+>
<!ATTLIST History
  xmlns CDATA #FIXED ''>

<!ELEMENT PublicationStatus (#PCDATA)>
<!ATTLIST PublicationStatus
  xmlns CDATA #FIXED ''>

<!ELEMENT ArticleIdList (ArticleId)+>
<!ATTLIST ArticleIdList
  xmlns CDATA #FIXED ''>

<!ELEMENT Journal (ISSN,JournalIssue,Title,ISOAbbreviation)>
<!ATTLIST Journal
  xmlns CDATA #FIXED ''>

<!ELEMENT ArticleTitle (#PCDATA)>
<!ATTLIST ArticleTitle
  xmlns CDATA #FIXED ''>

<!ELEMENT ELocationID (#PCDATA)>
<!ATTLIST ELocationID
  xmlns CDATA #FIXED ''
  EIdType NMTOKEN #REQUIRED
  ValidYN NMTOKEN #REQUIRED>

<!ELEMENT Abstract (AbstractText)>
<!ATTLIST Abstract
  xmlns CDATA #FIXED ''>

<!ELEMENT AuthorList (Author)+>
<!ATTLIST AuthorList
  xmlns CDATA #FIXED ''
  CompleteYN NMTOKEN #REQUIRED>

<!ELEMENT Language (#PCDATA)>
<!ATTLIST Language
  xmlns CDATA #FIXED ''>

<!ELEMENT PublicationTypeList (PublicationType)+>
<!ATTLIST PublicationTypeList
  xmlns CDATA #FIXED ''>

<!ELEMENT ArticleDate (Year,Month,Day)>
<!ATTLIST ArticleDate
  xmlns CDATA #FIXED ''
  DateType NMTOKEN #REQUIRED>

<!ELEMENT Country (#PCDATA)>
<!ATTLIST Country
  xmlns CDATA #FIXED ''>

<!ELEMENT MedlineTA (#PCDATA)>
<!ATTLIST MedlineTA
  xmlns CDATA #FIXED ''>

<!ELEMENT NlmUniqueID (#PCDATA)>
<!ATTLIST NlmUniqueID
  xmlns CDATA #FIXED ''>

<!ELEMENT ISSNLinking (#PCDATA)>
<!ATTLIST ISSNLinking
  xmlns CDATA #FIXED ''>

<!ELEMENT Keyword (#PCDATA)>
<!ATTLIST Keyword
  xmlns CDATA #FIXED ''
  MajorTopicYN NMTOKEN #REQUIRED>

<!ELEMENT PubMedPubDate (Year,Month,Day,Hour,Minute)>
<!ATTLIST PubMedPubDate
  xmlns CDATA #FIXED ''
  PubStatus NMTOKEN #REQUIRED>

<!ELEMENT ArticleId (#PCDATA)>
<!ATTLIST ArticleId
  xmlns CDATA #FIXED ''
  IdType NMTOKEN #REQUIRED>

<!ELEMENT ISSN (#PCDATA)>
<!ATTLIST ISSN
  xmlns CDATA #FIXED ''
  IssnType NMTOKEN #REQUIRED>

<!ELEMENT JournalIssue (PubDate)>
<!ATTLIST JournalIssue
  xmlns CDATA #FIXED ''
  CitedMedium NMTOKEN #REQUIRED>

<!ELEMENT Title (#PCDATA)>
<!ATTLIST Title
  xmlns CDATA #FIXED ''>

<!ELEMENT ISOAbbreviation (#PCDATA)>
<!ATTLIST ISOAbbreviation
  xmlns CDATA #FIXED ''>

<!ELEMENT AbstractText (#PCDATA)>
<!ATTLIST AbstractText
  xmlns CDATA #FIXED ''>

<!ELEMENT Author (LastName,ForeName,Initials,AffiliationInfo)>
<!ATTLIST Author
  xmlns CDATA #FIXED ''
  ValidYN NMTOKEN #REQUIRED>

<!ELEMENT PublicationType (#PCDATA)>
<!ATTLIST PublicationType
  xmlns CDATA #FIXED ''
  UI NMTOKEN #REQUIRED>

<!ELEMENT Hour (#PCDATA)>
<!ATTLIST Hour
  xmlns CDATA #FIXED ''>

<!ELEMENT Minute (#PCDATA)>
<!ATTLIST Minute
  xmlns CDATA #FIXED ''>

<!ELEMENT PubDate (Year,Month,Day)>
<!ATTLIST PubDate
  xmlns CDATA #FIXED ''>

<!ELEMENT LastName (#PCDATA)>
<!ATTLIST LastName
  xmlns CDATA #FIXED ''>

<!ELEMENT ForeName (#PCDATA)>
<!ATTLIST ForeName
  xmlns CDATA #FIXED ''>

<!ELEMENT Initials (#PCDATA)>
<!ATTLIST Initials
  xmlns CDATA #FIXED ''>

<!ELEMENT AffiliationInfo (Affiliation)>
<!ATTLIST AffiliationInfo
  xmlns CDATA #FIXED ''>

<!ELEMENT Affiliation (#PCDATA)>
<!ATTLIST Affiliation
  xmlns CDATA #FIXED ''>

<!ELEMENT Year (#PCDATA)>
<!ATTLIST Year
  xmlns CDATA #FIXED ''>

<!ELEMENT Month (#PCDATA)>
<!ATTLIST Month
  xmlns CDATA #FIXED ''>

<!ELEMENT Day (#PCDATA)>
<!ATTLIST Day
  xmlns CDATA #FIXED ''>

=== PulkitMathur/Databases/XML/asg2XML.xml
<?xml version="1.0"?>
<!DOCTYPE PubmedArticleSet PUBLIC "-//NLM//DTD PubMedArticle, 1st June 2018//EN" "asg2DTD.dtd">
<PubmedArticleSet>
<PubmedArticle>
    <MedlineCitation Status="Publisher" Owner="NLM">
        <PMID Version="1">30276571</PMID>
        <DateRevised>
            <Year>2018</Year>
            <Month>10</Month>
            <Day>02</Day>
        </DateRevised>
        <Article PubModel="Print-Electronic">
            <Journal>
                <ISSN IssnType="Electronic">1573-2568</ISSN>
                <JournalIssue CitedMedium="Internet">
                    <PubDate>
                        <Year>2018</Year>
                        <Month>Oct</Month>
                        <Day>01</Day>
                    </PubDate>
                </JournalIssue>
                <Title>Digestive diseases and sciences</Title>
                <ISOAbbreviation>Dig. Dis. Sci.</ISOAbbreviation>
            </Journal>
            <ArticleTitle>Utility of Esophageal High-Resolution Manometry in Clinical Practice: First, Do HRM.</ArticleTitle>
            <ELocationID EIdType="doi" ValidYN="Y">10.1007/s10620-018-5300-4</ELocationID>
            <Abstract>
                <AbstractText>Esophageal high-resolution manometry (HRM) has advanced the understanding of esophageal motor function and the ability to diagnose and manage disorders of esophageal motility. In this review, we describe the indications for and the technical performance of HRM. The Chicago classification of esophageal motor function, now in its third iteration, streamlines and standardizes the nomenclature and basic interpretation of HRM data depicted as Clouse topographic plots. In clinical practice, HRM is an important diagnostic test for patients with dysphagia as well as patients with suspected gastroesophageal reflux disease (GERD), particularly in those patients with a suboptimal symptomatic response to antisecretory therapy. HRM can support diagnoses such as achalasia, as well as provide evidence for behavioral disorders such as rumination syndrome or supragastric belching with the assistance of postprandial HRM with impedance. Further, the GERD classification of motor function introduces a three-part hierarchical evaluation of esophageal motor function in GERD, highlighting the value of assessment of esophageal contractile reserve through provocative maneuvers during HRM such as multiple rapid swallows.</AbstractText>
            </Abstract>
            <AuthorList CompleteYN="Y">
                <Author ValidYN="Y">
                    <LastName>Dhawan</LastName>
                    <ForeName>Ishita</ForeName>
                    <Initials>I</Initials>
                    <AffiliationInfo>
                        <Affiliation>Department of Medicine, Pennsylvania Hospital, University of Pennsylvania Health System, Philadelphia, PA, USA.</Affiliation>
                    </AffiliationInfo>
                </Author>
                <Author ValidYN="Y">
                    <LastName>O'Connell</LastName>
                    <ForeName>Brendon</ForeName>
                    <Initials>B</Initials>
                    <AffiliationInfo>
                        <Affiliation>Division of Gastroenterology, Durham Veterans Affairs Medical Center, Duke University School of Medicine, Durham, USA.</Affiliation>
                    </AffiliationInfo>
                </Author>
                <Author ValidYN="Y">
                    <LastName>Patel</LastName>
                    <ForeName>Amit</ForeName>
                    <Initials>A</Initials>
                    <AffiliationInfo>
                        <Affiliation>Division of Gastroenterology, Durham Veterans Affairs Medical Center, Duke University School of Medicine, Durham, USA.</Affiliation>
                    </AffiliationInfo>
                </Author>
                <Author ValidYN="Y">
                    <LastName>Schey</LastName>
                    <ForeName>Ron</ForeName>
                    <Initials>R</Initials>
                    <AffiliationInfo>
                        <Affiliation>Gastroenterology Section, Department of Medicine, Lewis Katz School of Medicine, Temple University School of Medicine, Philadelphia, PA, USA.</Affiliation>
                    </AffiliationInfo>
                </Author>
                <Author ValidYN="Y">
                    <LastName>Parkman</LastName>
                    <ForeName>Henry P</ForeName>
                    <Initials>HP</Initials>
                    <AffiliationInfo>
                        <Affiliation>Gastroenterology Section, Department of Medicine, Lewis Katz School of Medicine, Temple University School of Medicine, Philadelphia, PA, USA.</Affiliation>
                    </AffiliationInfo>
                </Author>
                <Author ValidYN="Y">
                    <LastName>Friedenberg</LastName>
                    <ForeName>Frank</ForeName>
                    <Initials>F</Initials>
                    <AffiliationInfo>
                        <Affiliation>Gastroenterology Section, Department of Medicine, Lewis Katz School of Medicine, Temple University School of Medicine, Philadelphia, PA, USA. frank.friedenberg@tuhs.temple.edu.</Affiliation>
                    </AffiliationInfo>
                </Author>
            </AuthorList>
            <Language>eng</Language>
            <PublicationTypeList>
                <PublicationType UI="D016428">Journal Article</PublicationType>
                <PublicationType UI="D016454">Review</PublicationType>
            </PublicationTypeList>
            <ArticleDate DateType="Electronic">
                <Year>2018</Year>
                <Month>10</Month>
                <Day>01</Day>
            </ArticleDate>
        </Article>
        <MedlineJournalInfo>
            <Country>United States</Country>
            <MedlineTA>Dig Dis Sci</MedlineTA>
            <NlmUniqueID>7902782</NlmUniqueID>
            <ISSNLinking>0163-2116</ISSNLinking>
        </MedlineJournalInfo>
        <KeywordList Owner="NOTNLM">
            <Keyword MajorTopicYN="N">Antireflux surgery (ARS)</Keyword>
            <Keyword MajorTopicYN="N">Chicago classification</Keyword>
            <Keyword MajorTopicYN="N">Esophageal high-resolution manometry (HRM)</Keyword>
            <Keyword MajorTopicYN="N">Gastroesophageal reflux disease (GERD)</Keyword>
        </KeywordList>
    </MedlineCitation>
    <PubmedData>
        <History>
            <PubMedPubDate PubStatus="entrez">
                <Year>2018</Year>
                <Month>10</Month>
                <Day>3</Day>
                <Hour>6</Hour>
                <Minute>0</Minute>
            </PubMedPubDate>
            <PubMedPubDate PubStatus="pubmed">
                <Year>2018</Year>
                <Month>10</Month>
                <Day>3</Day>
                <Hour>6</Hour>
                <Minute>0</Minute>
            </PubMedPubDate>
            <PubMedPubDate PubStatus="medline">
                <Year>2018</Year>
                <Month>10</Month>
                <Day>3</Day>
                <Hour>6</Hour>
                <Minute>0</Minute>
            </PubMedPubDate>
        </History>
        <PublicationStatus>aheadofprint</PublicationStatus>
        <ArticleIdList>
            <ArticleId IdType="pubmed">30276571</ArticleId>
            <ArticleId IdType="doi">10.1007/s10620-018-5300-4</ArticleId>
            <ArticleId IdType="pii">10.1007/s10620-018-5300-4</ArticleId>
        </ArticleIdList>
    </PubmedData>
</PubmedArticle>


<PubmedArticle>
    <MedlineCitation Status="In-Process" Owner="NLM">
        <PMID Version="1">30268301</PMID>
        <DateRevised>
            <Year>2018</Year>
            <Month>09</Month>
            <Day>30</Day>
        </DateRevised>
        <Article PubModel="Print">
            <Journal>
                <ISSN IssnType="Electronic">1558-5069</ISSN>
                <JournalIssue CitedMedium="Internet">
                    <Volume>28</Volume>
                    <Issue>4</Issue>
                    <PubDate>
                        <Year>2018</Year>
                        <Month>Nov</Month>
                    </PubDate>
                </JournalIssue>
                <Title>Thoracic surgery clinics</Title>
                <ISOAbbreviation>Thorac Surg Clin</ISOAbbreviation>
            </Journal>
            <ArticleTitle>The Role of Novel Functional Probes in the Evaluation and Treatment of Esophageal Disease.</ArticleTitle>
            <Pagination>
                <MedlinePgn>555-566</MedlinePgn>
            </Pagination>
            <ELocationID EIdType="pii" ValidYN="Y">S1547-4127(18)30105-1</ELocationID>
            <ELocationID EIdType="doi" ValidYN="Y">10.1016/j.thorsurg.2018.07.007</ELocationID>
            <Abstract>
                <AbstractText>The understanding of esophageal function and dysfunction in a variety of disease states has been driven largely by the introduction of a variety of measurement technologies. Included in these are contrast esophagram, computed tomography, high-resolution manometry, and 24-hour pH monitoring. Two novel measurement technologies, the functional lumen imaging probe (FLIP) and mucosal impedance (MI) catheter have recently introduced and studied. This review will discuss the technological basis of these tools and the evidence behind their application in the measurement of esophageal anatomy, physiology, and histology pertaining to a number of diseases, including gastroesophageal reflux disease, achalasia, and esosinophilic esophagitis.</AbstractText>
                <CopyrightInformation>Copyright Â© 2018 Elsevier Inc. All rights reserved.</CopyrightInformation>
            </Abstract>
            <AuthorList CompleteYN="Y">
                <Author ValidYN="Y">
                    <LastName>Teitelbaum</LastName>
                    <ForeName>Ezra N</ForeName>
                    <Initials>EN</Initials>
                    <AffiliationInfo>
