=== PulkitMathur/Databases/XML/My_Market.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="SHOP">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="CATEGORY">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="PRODUCT">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="NAME"></xs:element>
                                        <xs:element name="DESCRIPTION" type="xs:string"></xs:element>
                                        <xs:element name="PRICE" type="xs:int"></xs:element>
                                        <xs:element name="RATING" type="xs:string"></xs:element>
                                        <xs:element name="COMMENT">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="PERSON" type="xs:string"></xs:element>
                                                    <xs:element name="DATE" type="xs:date"></xs:element>
                                                    <xs:element name="DESC" type="xs:string"></xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            
                        </xs:sequence>
                        <xs:attribute name="NAME" use="required"></xs:attribute>
                    </xs:complexType>
                </xs:element>    
            </xs:sequence>
            <xs:attribute name="NAME" use="required"></xs:attribute>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== PulkitMathur/Databases/XML/My_Market_INT_DTD.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE SHOP[
    <!ELEMENT  SHOP (CATEGORY+)>
    <!ELEMENT CATEGORY (PRODUCT+) >
    <!ELEMENT PRODUCT (NAME,DESCRIPTION,PRICE,RATING,COMMENT*)>
    <!ELEMENT NAME (#PCDATA) >
    <!ELEMENT DESCRIPTION (#PCDATA) >
    <!ELEMENT PRICE (#PCDATA) >
    <!ELEMENT  RATING (#PCDATA) >
    <!ELEMENT COMMENT (PERSON,DATE,DESC) >
    <!ELEMENT  PERSON (#PCDATA) >
    <!ELEMENT DATE (#PCDATA) >
    <!ELEMENT DESC (#PCDATA) >
    
    <!ATTLIST SHOP NAME CDATA #REQUIRED	>
    <!ATTLIST CATEGORY NAME CDATA #REQUIRED	 >    
]>



<SHOP NAME="Zamazon" xmlns:xs="http://www.w3.org/2001/XMLSchema" 
    xs:schemaLocation="my_market.xsd"   >
    <CATEGORY NAME= "Computer"> 
        <PRODUCT>
            <NAME>Apple</NAME>
            <DESCRIPTION>A White Laptop with 2GB RAM and i5 Processor</DESCRIPTION>
            <PRICE>750</PRICE>
            <RATING>9</RATING>
        </PRODUCT>
        <PRODUCT>
            <NAME>HP</NAME>
            <DESCRIPTION>Red Laptop with 16GB RAM and i7 Processor</DESCRIPTION>
            <PRICE>800</PRICE>
            <RATING>6</RATING>
        </PRODUCT>
    </CATEGORY>
    
    <CATEGORY NAME= "Electronics"> 
        <PRODUCT>
            <NAME>Samsung</NAME>
            <DESCRIPTION>White phone with 5.8 inches OLED screen and Cynaogen OS</DESCRIPTION>
            <PRICE>200</PRICE>
            <RATING>4</RATING>
        </PRODUCT>
        <PRODUCT>
            <NAME>iPhone XS</NAME>
            <DESCRIPTION>Rose Gold phone bezel less phone with Super AMLOED Screen</DESCRIPTION>
            <PRICE>1146</PRICE>
            <RATING>9</RATING>
            <COMMENT>
                <PERSON>Rohit Roy</PERSON>
                <DATE>5/11/18</DATE>
                <DESC>Best iPhone ever!!</DESC>
            </COMMENT>
        </PRODUCT>
    </CATEGORY>
    
    <CATEGORY NAME= "Clothing"> 
        <PRODUCT>
            <NAME>Raymonds</NAME>
            <DESCRIPTION>Black Suite</DESCRIPTION>
            <PRICE>1000</PRICE>
            <RATING>7</RATING>
        </PRODUCT>
        
        <PRODUCT>
            <NAME>Levis</NAME>
            <DESCRIPTION>Jeans</DESCRIPTION>
            <PRICE>50</PRICE>
            <RATING>6</RATING>
        </PRODUCT>
    </CATEGORY>
</SHOP>
